* markov-twit

** Description
A small project using Markov chains and the Twitter and Reddit api to generate tweets and Reddit comments in the style of a particular user, or posts and titles for a given subreddit. The code is based on the tutorial found at [[http://howistart.org/posts/clojure/1/]].

To see the code in action, visit the app on [[https://markov-twit.herokuapp.com/][Heroku]].

** Usage
#+BEGIN_SRC clojure
(generate-tweet "twitter-user" 10)
#+END_SRC
Pulls the 200 most recent tweets from the timeline of @TwitterUser, creates a Markov chain and walks the chain 10 times to generate new tweets, starting each time from the beginning of a random tweet.
The function also accepts parameters deciding the max length of the generated texts (defaults to 280) and amount of text the Markov chain uses to generate the next word (default 2).

#+BEGIN_SRC clojure
(generate-reddit-comment "reddit-user")
(generate-reddit-title "subreddit")
(generate-reddit-post "subreddit")
#+END_SRC
Exactly the same, except they use the Reddit API to pull 200 comments, titles or posts respectively to generate the Markov chain.

#+BEGIN_SRC clojure
(generate-file ["file1", "file2", ...])
#+END_SRC
Builds the Markov chain from the contents of all the files.

** Setup
The project was created using [[https://leiningen.org/][Leiningen]]. To get Twitter integration to work, you need a =profiles.clj= file in the project root directory, containing the following:
#+BEGIN_SRC clojure
{:dev  {:env {:app-consumer-key "twitter-key"
              :app-consumer-secret "twitter-secret"
              :user-access-token "twitter-key-2"
              :user-access-secret "twitter-secret-2"}}}
#+END_SRC
A guide for how to get the values to put in this file can be found [[http://howistart.org/posts/clojure/1/#hooking-the-bot-up-to-twitter][here]].
